apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-gke
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-actions-gke
  template:
    metadata:
      labels:
        app: github-actions-gke
    spec:
      containers:
      - name: spring-api
        image: xiu0327/spring-api-test